interview/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import blog.views
import account.views as account

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog.views.home, name="home"),
    path('blog/all_list', blog.views.all_list, name="all_list"),
    path("blog/<int:blog_id>", blog.views.detail, name="detail"),
    path('blog/new', blog.views.new, name="new"),
    path('blog/create', blog.views.create, name="create"),
    path('blog/edit/<int:blog_id>', blog.views.edit, name="edit"),
    path('blog/update/<int:blog_id>', blog.views.update, name="update"),
    path('blog/delete/<int:blog_id>', blog.views.delete, name="delete"),
    path('blog/<int:blog_id>/comment',
         blog.views.add_comment_to_post, name="add_comment_to_post"),

    path('account/login', account.login_view, name="login"),
    path('account/logout', account.logout_view, name="logout"),
    path('account/register', account.register_view, name="register"),

    path('delete_comment/<int:blog_id>/<int:comment_id>',
         blog.views.delete_comment, name="delete_comment"),
    path('blog/edit_comment/<int:blog_id>/<int:comment_id>',
         blog.views.edit_comment, name="edit_comment"),
    path('blog/update_comment/<int:comment_id>',
         blog.views.update_comment, name="update_comment"),

    path('blog/cate01', blog.views.cate01, name="cate01"),
    path('blog/cate02', blog.views.cate02, name="cate02"),
    path('blog/search', blog.views.search, name="search"),
    path('blog/search01', blog.views.search01, name="search01"),
    path('blog/search02', blog.views.search02, name="search02"),

    path('blog/mypage', blog.views.mypage, name="mypage"),
    path('blog/like', blog.views.likes, name="likes"),
    path('account/edit_user', account.edit_user, name="edit_user"),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from account.models import CustomUser
# Create your models here.


class Category(models.Model):
    category_name = models.CharField(max_length=30)
    parent = models.ForeignKey(
        'self', on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        unique_together = ["category_name"]

    def __str__(self):
        return self.category_name


class HashTag(models.Model):
    hashtag_name = models.CharField(max_length=100)

    def __str__(self):
        return self.hashtag_name


class Blog(models.Model):
    writer = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    body = models.TextField()
    hashtag = models.ManyToManyField(HashTag)
    like = models.ManyToManyField(CustomUser, related_name='likes', blank=True)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:70]


class Comment(models.Model):
    post = models.ForeignKey(
        Blog, related_name="comments", on_delete=models.CASCADE)
    author_name = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, null=True)
    comment_text = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    def approve(self):
        self.save()

    def __str__(self):
        return self.comment_text

blog/forms.py
from django import forms
from django.db import models
from django.forms import fields
from .models import Blog, Comment, Category


class BlogForm(forms.ModelForm):
    class Meta:  # 일종의 이름표 역할
        model = Blog
        fields = ['category', 'title', 'body', 'image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment_text',)

blog/views.py
from django.shortcuts import redirect, render, get_object_or_404, redirect
from .models import Blog, Comment, HashTag
from django.utils import timezone
from .forms import BlogForm, CommentForm
from django.views.generic import ListView
from django.http import HttpResponse, JsonResponse
import json
# Create your views here.


def home(request):
    blog = Blog.objects.order_by('-pub_date')  # query set!
    return render(request, 'home.html', {'blogs': blog})


def all_list(request):
    blog = Blog.objects.order_by('-pub_date')  # query set!
    return render(request, 'all_list.html', {'blogs': blog})


def detail(request, blog_id):
    blog_detail = get_object_or_404(Blog, pk=blog_id)
    blog_hashtag = blog_detail.hashtag.all()
    return render(request, 'detail.html', {'blog': blog_detail, 'hashtags': blog_hashtag})


def new(request):
    form = BlogForm()
    return render(request, 'new.html', {'form': form})


def create(request):
    form = BlogForm(request.POST, request.FILES)
    if form.is_valid():
        new_blog = form.save(commit=False)
        new_blog.pub_date = timezone.now()
        new_blog.writer = request.user
        new_blog.save()
        hashtags = request.POST['hashtags']
        hashtag = hashtags.split(",")
        if 'image' in request.FILES:
            image = request.FILES['image']
        for tag in hashtag:
            ht = HashTag.objects.get_or_create(hashtag_name=tag)
            new_blog.hashtag.add(ht[0])
        return redirect('detail', new_blog.id)
    return redirect('home')


def edit(request, blog_id):
    blog_detail = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'edit.html', {'blog': blog_detail})


def update(request, blog_id):
    blog_update = get_object_or_404(Blog, pk=blog_id)
    blog_update.title = request.POST['title']
    blog_update.body = request.POST['body']
    if 'image' in request.FILES:
        blog_update.image = request.FILES['image']
    blog_update.save()
    return redirect('detail', blog_id)


def delete(request, blog_id):
    blog_delete = get_object_or_404(Blog, pk=blog_id)
    blog_delete.delete()
    return redirect('home')


def add_comment_to_post(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author_name = request.user
            comment.post = blog
            comment.save()
            return redirect('detail', blog_id)
    else:
        form = CommentForm()
    return render(request, 'add_comment_to_post.html', {'form': form})


def delete_comment(request, blog_id, comment_id):  # 댓글 삭제하기
    comment_delete = Comment.objects.get(id=comment_id)
    comment_delete.delete()
    return redirect('detail', blog_id)


def edit_comment(request, blog_id, comment_id):  # 댓글 수정하기
    comment = Comment.objects.get(id=comment_id)
    return render(request, 'edit_comment.html', {'comment': comment})


def update_comment(request, comment_id):
    comment_update = Comment.objects.get(id=comment_id)
    comment_update.comment_text = request.POST['comment_text']
    comment_update.save()
    return redirect('home')


def cate01(request):
    blogs = Blog.objects.all().filter(category_id=1).order_by('-pub_date')
    return render(request, 'cate01.html', {'blogs': blogs})


def cate02(request):
    blogs = Blog.objects.all().filter(category_id=2).order_by('-pub_date')
    return render(request, 'cate02.html', {'blogs': blogs})


def search(request):
    if request.method == 'POST':
        keyword = request.POST.get('keyword')
        hashtag = HashTag.objects.filter(hashtag_name=keyword)
        blog = Blog.objects.filter(hashtag__in=hashtag).order_by('-pub_date')
        return render(request, 'search.html', {'blogs': blog, 'keyword': keyword})
    elif request.method == 'GET':
        return redirect('/')


def search01(request):
    if request.method == 'POST':
        keyword = request.POST.get('keyword')
        hashtag = HashTag.objects.filter(hashtag_name=keyword)
        blog = Blog.objects.filter(
            hashtag__in=hashtag, category_id=1).order_by('-pub_date')
        return render(request, 'Search01.html', {'blogs': blog, 'keyword': keyword})
    elif request.method == 'GET':
        return redirect('/')


def search02(request):
    if request.method == 'POST':
        keyword = request.POST.get('keyword')
        hashtag = HashTag.objects.filter(hashtag_name=keyword)
        blog = Blog.objects.filter(
            hashtag__in=hashtag, category_id=2).order_by('-pub_date')
        return render(request, 'Search01.html', {'blogs': blog, 'keyword': keyword})
    elif request.method == 'GET':
        return redirect('/')


def mypage(request):
    myblog = Blog.objects.filter(writer=request.user)
    user_info = request.user
    user_like = request.user.likes.all()
    return render(request, 'mypage.html', {'myblogs': myblog, 'user_infos': user_info, 'user_likes': user_like, })


def likes(request):
    if request.is_ajax():  # ajax 방식일 때 아래 코드 실행
        blog_id = request.GET['blog_id']  # 좋아요를 누른 게시물id (blog_id)가지고 오기
        post = Blog.objects.get(id=blog_id)

        if not request.user.is_authenticated:  # 버튼을 누른 유저가 비로그인 유저일 때
            message = "로그인 하세요"  # 화면에 띄울 메세지
            context = {'like_count': post.like.count(), "message": message}
            return HttpResponse(json.dumps(context), content_type='application/json')

        user = request.user  # request.user : 현재 로그인한 유저
        if post.like.filter(id=user.id).exists():  # 이미 좋아요를 누른 유저일 때
            post.like.remove(user)  # like field에 현재 유저 추가
            message = "즐겨찾기 취소"  # 화면에 띄울 메세지
        else:  # 좋아요를 누르지 않은 유저일 때
            post.like.add(user)  # like field에 현재 유저 삭제
            message = "즐겨찾기 추가"  # 화면에 띄울 메세지
        # post.like.count() : 게시물이 받은 좋아요 수
        context = {'like_count': post.like.count(), "message": message}
        return HttpResponse(json.dumps(context), content_type='application/json')

blog/templates/add_comment_to_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>댓글달기</title>
    <link href="https://fonts.googleapis.com/css2?family=Syncopate:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Hahmlet&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/base_gnb.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/comment.css" />
</head>
<body>
    {% extends 'base_gnb.html' %}
    {% block content %}
    <div class = "wrap02">
        <div class = com_form>
            <h1>New comment</h1>
            <form method="POST" class = "post-form"> 
            {% csrf_token %}
            <div class = "newform_wrap">
                <label for="id_comment_text">댓글내용</label><br>
                <textarea name="comment_text" cols="40" rows="10" required="" id="id_comment_text"></textarea>
            </div>
            <button type = "submit" class="save btn btn-default">Send</button>
            </form>
        </div>
    </div>
    {% endblock %}
</body>
</html>

blog/templates/all_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All List</title>
    <link href="https://fonts.googleapis.com/css2?family=Syncopate:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Hahmlet&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/base_gnb.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/all_list.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/base_nav.css" />
</head>
<body>
  {% extends 'base_gnb.html' %}
  {% block content %}
    <div class = "wrap02">
      <div><p>전체 글 목록</p></div>
      <div><p>웹사이트의 전체 글을 확인할 수 있습니다.</p></div>
    </div>
    <div class = "wrap_form">
      <form class = "search" method='POST' action="{% url 'search' %}">
        {% csrf_token %}
        <input type="text" name="keyword" placeholder="현재게시판에서 태그로 검색">
        <button class="button" type="submit">검색</button>
      </form>
    </div>
    <div class = "wrap03">
      <div>
        {% for blog in blogs.all %}
        <a href="{% url 'detail' blog.id %}">
          <div class = "blog_post" >
            <div class = "top_line"></div>
            <p class = "blog_info">{{ blog.pub_date }}<br>
              {{ blog.category }}</p>
            <h1 class = "blog_title">{{ blog.title}}</h1>
            <div class = "image_wrap">
              {% if blog.image %}
              <img class="blog_image" src="{{ blog.image.url }}">
              {% endif %}
              {% if not blog.image %}
              <div>No Image</div>
              {% endif %}
            </div>
            <p class = "blog_sum">{{ blog.summary }}...</p>
            <a class = "more" href="{% url 'detail' blog.id %}">...more</a>
          </div>
        </a>
        {% endfor %}
      </div>
    </div>
    <div class = "nav_wrap">
      <div class = "nav_card">
        <a href="{% url 'all_list' %}"><p>All Post</p></a>
        <a href="{% url 'cate01' %}"><p>Interviewer</p></a>
        <a href="{% url 'cate02' %}"><p>Interviewee </p></a>
        {% if user.is_authenticated %}
          <a href="{% url 'new' %}"><p>Write</p></a>
        {% endif %}
      </div>
    </div>
  {% endblock %}
</body>
</html>

blog/templates/base_gnb.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>base_gnb</title>
</head>
<body>
  {%load static%}
  <div class = "wrap01">
    <div class = "top_gnb">
      <ul>
        <div><a href="{% url 'home' %}"><img class = "logo" src="{%static 'interweaver01.png'%}" alt="logo"></a></div>
      </ul>
      <ul>
        {% if not user.is_authenticated %}
          <li class="nav-item"><a href="{% url 'login' %}">Login</a></li>
          <li class="nav-item"><a href="{% url 'register' %}">Signup</a></li>
        {% endif %}
        {% if user.is_authenticated %}
          <li class="nav-item"><a href="{% url 'logout' %}">Logout</a></li>
          <li class="nav-item"><a href="{% url 'mypage' %}">MyPage</a></li>
        {% endif %}
      </ul>
      <ul>
        <li class="nav-item"><a href="{% url 'all_list' %}">전체 글 목록</a></li>
        <li class="nav-item"><a href="{% url 'cate01' %}">인터뷰어 구하기</a></li>
        <li class="nav-item"><a href="{% url 'cate02' %}">인터뷰이 구하기</a></li>
        {% if user.is_authenticated %}
          <li class="nav-item"><a href="{% url 'new' %}">글쓰기</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
  {% block content %}
  {% endblock %}
</body>
</html>

blog/templates/cate01.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Category01</title>
    <link href="https://fonts.googleapis.com/css2?family=Syncopate:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Hahmlet&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/base_gnb.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/cate01.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/base_nav.css" />
</head>
<body>
    {% extends 'base_gnb.html' %}
    {% block content %}
    <div class = "wrap02">
        <div><p>인터뷰어 구하기</p></div>
        <div><p>인터뷰 대상자를 구하는 인터뷰어를 찾을 수 있습니다.</p></div>
    </div>
    <div class = "wrap_form">
        <form class = "search" method='POST' action="{% url 'search01' %}">
            {% csrf_token %}
            <input type="text" name="keyword" placeholder="현재게시판에서 태그로 검색">
            <button class="button" type="submit">검색</button>
        </form>
    </div>
    <div class = "wrap03">
        <div>
            {% for blog in blogs.all %}
            <a href="{% url 'detail' blog.id %}">
            <div class = "blog_post" >
                <div class = "top_line"></div>
                <p class = "blog_info">
                    {{ blog.pub_date }}<br>
                    {{ blog.category }}
                </p>
                <h1 class = "blog_title">{{ blog.title}}</h1>
                <div class = "image_wrap">
                {% if blog.image %}
                <img class="blog_image" src="{{ blog.image.url }}">
                {% endif %}
                {% if not blog.image %}
                <div>No Image</div>
                {% endif %}
            </div>
            <p class = "blog_sum">{{ blog.summary }}...</p>
            <a class = "more" href="{% url 'detail' blog.id %}">...more</a>
            </div>
        </a>
        {% endfor %}
        </div>
    </div>
    <div class = "nav_wrap">
        <div class = "nav_card">
            <a href="{% url 'all_list' %}"><p>All Post</p></a>
            <a href="{% url 'cate01' %}"><p>Interviewer</p></a>
            <a href="{% url 'cate02' %}"><p>Interviewee </p></a>
            {% if user.is_authenticated %}
            <a href="{% url 'new' %}"><p>Write</p></a>
            {% endif %}
        </div>
    </div>
    {% endblock %}
</body>
</html>

blog/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>글 수정하기</title>
    <link href="https://fonts.googleapis.com/css2?family=Syncopate:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Hahmlet&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/base_gnb.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/edit.css" />
</head>
<body>
    {% extends 'base_gnb.html' %}
    {% block content %}
    <div class = "wrap02">
        <div class = edit_form>
            <h1>Editing Blog</h1>
            <form action = "{% url 'update' blog.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class = "newform_wrap">
                <label for="id_title">제목</label><br>
                <input type = "text" name = "title" value = "{{ blog.title }}">
            </div>
            <div class = "newform_wrap">
                <label for="id_title">본문</label><br>
                <textarea name = "body" id = "" cols = "30" rows = "20" >{{ blog.body }}</textarea>
            </div>
            <div class = "newform_wrap">
                <label for="id_image">이미지</label><br>
                <input class = "new_image" type="file" type="img" name="image">
            </div>
            <button type = "submit">제출</button>
        </div>
    </div>
    {% endblock %}
</form>
</body>
</html>

blog/templates/edit_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Comment</title>
    <link href="https://fonts.googleapis.com/css2?family=Syncopate:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Hahmlet&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/base_gnb.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/comment.css" />
</head>
<body>
    {% extends 'base_gnb.html' %}
    {% block content %}
    <div class = "wrap02">
        <div class = com_form>
            <h1>Edit comment</h1>
            <form action="{% url 'update_comment' comment.id %}" method="post">
            {% csrf_token %}
            <div class = "newform_wrap">
                <label for="id_comment_text">댓글내용</label><br>
                <textarea name="comment_text" id="" cols="30" rows="10">{{ comment.comment_text }}</textarea>
            </div>
            <button type="submit">제출</button>
            </form>
        </div>
    
        </form>
    </div>
    {% endblock %}
</body>
</html>

blog/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link href="https://fonts.googleapis.com/css2?family=Syncopate:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Hahmlet&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/base_gnb.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/home01.css" />
  </head>
<body>
  {% extends 'base_gnb.html' %}
  {%load static%}
  {% block content %}
  <div class = "wrap02">
    <div><img class = "logo_photo" src="{%static 'logo_type.png'%}" alt="logo_photo" /></div>
    <div><img class = "main_photo" src="{%static 'back03.png'%}" alt="main_photo" /></div>
  </div>
  <div class = "wrap_form">
    <form class = "search" method='POST' action="{% url 'search' %}">
      {% csrf_token %}
      <input type="text" name="keyword" placeholder="전체게시판에서 태그로 검색">
      <button class="button" type="submit">검색</button>
    </form>
  </div>
  <div class = "wrap03">
    <div><p>원하는 분야의 인터뷰이,<br>인터뷰어를 구할 수 있는곳</p></div>
    <div>
      <p>
        인터위버는 과제수행이나 자료조사를 위해서 인터뷰 대상자를 구하는 인터뷰어,<br>
        혹은 자기홍보를 위해 인터뷰 참여를 원하는 인터뷰이들을<br>탐색할 수 있는 웹사이트입니다.
      </p>
    </div>
  </div>
  <div class = "empty_div">
    <div>ⓒ 2021. interweaver all rights reserved.</div>
  </div>
  {%endblock%}
</body>
</html>

blog/templates/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>새로운 글 쓰기</title>
    <link href="https://fonts.googleapis.com/css2?family=Syncopate:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Hahmlet&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/base_gnb.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/new.css" />
</head>
<body>
    {% extends 'base_gnb.html' %}
    {% block content %}
    <div class = "wrap02">
        <div class = "new_form">
            <h1>New Post</h1>
            <form class = "new_form02" action = "{% url 'create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class = "newform_wrap">
                <label for="id_category">카테고리</label><br>
                <select name="category" required="" id="id_category">
                    <option value="" selected="">---------</option>
                    <option value="1">인터뷰어 구하기</option>
                    <option value="2">인터뷰이 구하기</option>
                </select>
            </div>
            <div class = "newform_wrap">
                <label for="id_title">제목</label><br>
                <input type="text" name="title" maxlength="200" required="" id="id_title">
            </div>
            <div class = "newform_wrap">
                <label for="id_body">본문</label><br>
                <textarea name="body" cols="40" rows="10" required="" id="id_body"></textarea>
            </div>
            <div class = "newform_wrap">
                <label for="id_image">해시태그</label><br>
                <input type="text" name="hashtags" placeholder="해시태그 ,로 구분">
            </div>
            <div class = "newform_wrap">
                <label for="id_image">이미지</label><br>
                <input class = "new_image" type="file" name="image" accept="image/*" id="id_image">
            </div>
            <button type="submit">제출</button>
        </form>
        </div>
    </div>
    {% endblock %}
</body>
</html>