interview/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import blog.views
import account.views as account

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog.views.home, name="home"),
    path('blog/all_list', blog.views.all_list, name="all_list"),
    path("blog/<int:blog_id>", blog.views.detail, name="detail"),
    path('blog/new', blog.views.new, name="new"),
    path('blog/create', blog.views.create, name="create"),
    path('blog/edit/<int:blog_id>', blog.views.edit, name="edit"),
    path('blog/update/<int:blog_id>', blog.views.update, name="update"),
    path('blog/delete/<int:blog_id>', blog.views.delete, name="delete"),
    path('blog/<int:blog_id>/comment',
         blog.views.add_comment_to_post, name="add_comment_to_post"),

    path('account/login', account.login_view, name="login"),
    path('account/logout', account.logout_view, name="logout"),
    path('account/register', account.register_view, name="register"),

    path('delete_comment/<int:blog_id>/<int:comment_id>',
         blog.views.delete_comment, name="delete_comment"),
    path('blog/edit_comment/<int:blog_id>/<int:comment_id>',
         blog.views.edit_comment, name="edit_comment"),
    path('blog/update_comment/<int:comment_id>',
         blog.views.update_comment, name="update_comment"),

    path('blog/cate01', blog.views.cate01, name="cate01"),
    path('blog/cate02', blog.views.cate02, name="cate02"),
    path('blog/search', blog.views.search, name="search"),
    path('blog/search01', blog.views.search01, name="search01"),
    path('blog/search02', blog.views.search02, name="search02"),

    path('blog/mypage', blog.views.mypage, name="mypage"),
    path('blog/like', blog.views.likes, name="likes"),
    path('account/edit_user', account.edit_user, name="edit_user"),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
# Create your models here.


class CustomUser(AbstractUser):
    nickname = models.CharField(max_length=100)
    location = models.CharField(max_length=200)

account/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
from django.contrib.auth import get_user_model


class RegisterForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password1', 'password2',
                  'nickname', 'location']


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'nickname', 'location']

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
# Create your views here.
from .forms import RegisterForm, CustomUserChangeForm


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(
                request=request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
        else:
            return HttpResponse('로그인실패, 아이디와 비밀번호를 재확인하세요')
    else:
        form = AuthenticationForm()
        return render(request, 'login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('home')


def register_view(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = RegisterForm()
        return render(request, 'signup.html', {'form': form})


def edit_user(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = CustomUserChangeForm(instance=request.user)
        return render(request, 'edit_user.html', {'form': form})

account/templates/edit_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원정보 수정</title>
    <link href="https://fonts.googleapis.com/css2?family=Syncopate:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Hahmlet&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/base_gnb.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/edit_user.css" />
</head>
<body>
    {% extends 'base_gnb.html' %}
    {% block content %}
    <div class = "wrap02">
        <div class = "edit_form">
            <h1>회원 정보 수정</h1>
            <form action="{% url 'edit_user' %}" method="POST">
                {% csrf_token%}
                <div>
                    <label for="id_username">아이디</label>
                    <input type="text" name="username" value="{{ user.username }}" maxlength="150" required="" id="id_username">
                    <div class="helptext01">150 characters or fewer. Letters, digits and @/./+/-/_ only.</div>
                </div>
                <div>
                    <label for="id_nickname">닉네임</label>
                    <input type="text" name="nickname" value="{{ user.nickname }}" maxlength="100" required="" id="id_nickname">
                </div>
                <div>
                    <label for="id_location">위치</label>
                    <input type="text" name="location" value="{{ user.location }}" maxlength="200" required="" id="id_location">
                </div>
                <button type="submit">제출</button>
            </form>
        </div>
    </div>
    {% endblock %}
</body>
</html>

account/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>로그인</title>
    <link href="https://fonts.googleapis.com/css2?family=Syncopate:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Hahmlet&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/base_gnb.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/login.css" />
</head>
<body>
    {% extends 'base_gnb.html' %}
    {% block content %}
    <div class = "wrap02">
        <div class = "login_form">
            <h1>Login</h1>
            <form action = "{% url 'login' %}" method="POST" class = "login_form">
            {% csrf_token %}
            <div calss = "newform_wrap">
                <label for="id_username">아이디</label><br>
                <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="100" required="" id="id_username">
            </div>
            <div calss = "newform_wrap">
                <label for="id_password">비밀번호</label><br>
                <input type="password" name="password" autocomplete="current-password" required="" id="id_password">
            </div calss = "newform_wrap">
            <div><a href="{% url 'register' %}" class="signup_text">회원이 아니세요? 회원가입하세요.</a></div>
            <button type="submit">로그인</button>
        </div>
    </div>
</form>
{% endblock %}
</body>
</html>

account/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원가입</title>
    <link href="https://fonts.googleapis.com/css2?family=Syncopate:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Hahmlet&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/base_gnb.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/signup.css" />
</head>
<body>
    {% extends 'base_gnb.html' %}
    {% block content %}
    <div class = "wrap02">
        <div class = "singup_form">
            <h1>Sign Up</h1>
            <form action = "{% url 'register' %}" method="POST">
            {% csrf_token %}
            <div class = "newform_wrap">
                <label for="id_username">아이디</label><br>
                <input type="text" name="username" maxlength="150" autofocus="" required="" id="id_username">
                <div class="helptext01">150 characters or fewer. Letters, digits and @/./+/-/_ only.</div>
            </div>
            <div class = "newform_wrap">
                <label for="id_password1">비밀번호</label><br>
                <input type="password" name="password1" autocomplete="new-password" required="" id="id_password1">
            </div>
            <div class = "newform_wrap">
                <ul class="helptext02">
                    <li>Your password must contain at least 8 characters.</li>
                    <li>Your password can’t be a commonly used password.</li>
                    <li>Your password can’t be entirely numeric.</li>
                </ul>
            </div>
            <div class = "newform_wrap">
                <label for="id_password2">비밀번호 재입력</label><br>
                <input type="password" name="password2" autocomplete="new-password" required="" id="id_password2">
                <div class="helptext01">Enter the same password as before, for verification.</div>
            </div>
            <div class = "newform_wrap">
                <label for="id_nickname">닉네임</label><br>
                <input type="text" name="nickname" maxlength="100" required="" id="id_nickname">
            </div>
            <div class = "newform_wrap">
                <label for="id_location">위치</label><br>
                <input type="text" name="location" maxlength="200" required="" id="id_location">
            </div>
            <button type="submit">회원가입</button>
        </div>
    </div>
    {% endblock %}
</form>
</body>
</html>